"""initial migration

Revision ID: fdc1f7d3fbe3
Revises: 5e7e69a05afe
Create Date: 2026-09-14 22:17:03.138717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc1f7d3fbe3'
down_revision: Union[str, Sequence[str], None] = '5e7e69a05afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_user_access_token'), 'user', ['access_token'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('iban', sa.String(), nullable=False),
    sa.Column('bank_code', sa.Enum('DEMO_BANK', name='bankcodeenum'), nullable=False),
    sa.Column('cvv', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('payment_system', sa.Enum('VISA', 'MASTERCARD', name='paymentsystemenum'), nullable=False),
    sa.Column('card_type', sa.Enum('DEBIT', 'CREDIT', 'OVERDRAFT', name='cardtypeenum'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('UAH', 'USD', 'EUR', name='currencyenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_card_number'), 'card', ['card_number'], unique=True)
    op.create_index(op.f('ix_card_iban'), 'card', ['iban'], unique=True)
    op.create_index(op.f('ix_card_user_id'), 'card', ['user_id'], unique=False)
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', name='operationtypeenum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('UAH', 'USD', 'EUR', name='currencyenum'), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_card_id'), 'operation', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_card_id'), table_name='operation')
    op.drop_table('operation')
    op.drop_index(op.f('ix_card_user_id'), table_name='card')
    op.drop_index(op.f('ix_card_iban'), table_name='card')
    op.drop_index(op.f('ix_card_card_number'), table_name='card')
    op.drop_table('card')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_access_token'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
